version: '3.5'
services:
  db:
    image: postgres:12
    env_file:
     - .env
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    command: postgres -c shared_buffers=384MB -c max_connections=400 -c log_min_messages=FATAL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rinha

  api1: &api
    build: .
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.6GB'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: >
      bash -c "
      alembic upgrade head
      && uvicorn rinha.api.main:app --host 0.0.0.0 --port 8000 --reload --timeout-keep-alive 500 --no-access-log"
    networks:
      - rinha

  api2:
    <<: *api
    command: >
      bash -c "uvicorn rinha.api.main:app --host 0.0.0.0 --port 8001 --reload --timeout-keep-alive 500 --no-access-log"

  nginx:
    image: nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_started
      api2:
        condition: service_started
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    ports:
      - "9999:9999"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.3GB'
networks:
  rinha:
    driver: bridge
